services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-open-webui-ui-rag
    ports:
      - "8080:8080"
    volumes:
#      - ~/.open-webui:/app/backend/data
      - ./docker/local/open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - RAG_EMBEDDING_MODEL=${RAG_EMBEDDING_MODEL}
      - RAG_EMBEDDING_BATCH_SIZE=${RAG_EMBEDDING_BATCH_SIZE}
      - RAG_RERANKING_MODEL=${RAG_RERANKING_MODEL}
      - CHUNK_SIZE=${CHUNK_SIZE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

